#ifndef SK_BYTECODE_H
#define SK_BYTECODE_H

enum Bytecode_t {
	BYTECODE_MOV_REG_REG = 0x01,
	BYTECODE_MOV_REG_CONST = 0x02,
	BYTECODE_PUSH_CONST = 0x11,
	BYTECODE_ADD_REG_REG = 0x20,
	BYTECODE_ADD_STACK = 0x22,
	BYTECODE_SUB_STACK = 0x25,
	BYTECODE_MUL_REG_REG = 0x26,
	BYTECODE_MUL_STACK = 0x28,
	BYTECODE_DIV_STACK = 0x2B,
	BYTECODE_INC = 0x2C,
	BYTECODE_JMP = 0x30,
	BYTECODE_CMP_REG_REG = 0x31,
	BYTECODE_CMP_REG_NUM = 0x32,
	BYTECODE_JE = 0x33,
	BYTECODE_JNE = 0x34,
	BYTECODE_JGT = 0x35,
	BYTECODE_JGE = 0x36,
	BYTECODE_JLT = 0x37,
	BYTECODE_JLE = 0x38,
	BYTECODE_JZ = 0x39,
	BYTECODE_JNZ = 0x3A,
	BYTECODE_CALL = 0x3B,
	BYTECODE_RET = 0x3C,
	BYTECODE_HELLO = 0xFE,
	BYTECODE_HLT = 0xFF
};
typedef enum Bytecode_t Bytecode;

enum BytecodeRegister_t {
	BYTECODE_REGISTER_AX = 0x01,
	BYTECODE_REGISTER_BX = 0x02,
	BYTECODE_REGISTER_CX = 0x03,
	BYTECODE_REGISTER_DX = 0x04,
	BYTECODE_REGISTER_RX = 0x05,
	BYTECODE_REGISTER_SP = 0x06,
	BYTECODE_REGISTER_BP = 0x07,

	BYTECODE_REGISTER_SIZE = 0x08,
};
typedef enum BytecodeRegister_t BytecodeRegister;

enum ConstantSize_t {
	CONSTANT_SIZE_BYTE = 1,
	CONSTANT_SIZE_SHORT = 2,
	CONSTANT_SIZE_INT = 4
};
typedef enum ConstantSize_t ConstantSize;

#endif // SK_BYTECODE_H